### ISSUE TITLE
arduino what to use?

### ISSUE THREAD

**Issue by muhammadzikrullah** [7Rocky/IoT_Microservices#1]
i dont know what kind arduino should i try this iot_microservice, maybe you can add some readme.md for what kind arduino should using

**Comment by 7Rocky** [comment]
Hi,

I recommend using Arduino Uno WiFi Rev2 (https://store.arduino.cc/arduino-uno-wifi-rev2) and a Grove Temperature sensor (https://store.arduino.cc/grove-temperature-sensor), which are the onse I've been using in this project. Otherwise, you may use another Arduino board that supports WiFi connection or get a WiFi module, but I'm not sure if it would have the same features.

Hope it is useful 😁
